name: Release

on:
  push:
    tags:
      - "v*.*"

env:
  BUILD_RELEASE: 1

jobs:
  test-darwin:
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache ~/.stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ matrix.os }}
      - name: Install build prerequisites
        run: brew install argp-standalone haskell-stack protobuf-c util-linux
      - name: Build Acton
        run: make -C ${{ github.workspace }}
      - name: Build a release
        run: make -C ${{ github.workspace }} release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: acton-${{ matrix.os }}
          path: ${{ github.workspace }}/acton-darwin-x86_64*
          if-no-files-found: error
      - name: Run tests
        run: make -C ${{ github.workspace }} test


  test-linux:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache ~/.stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}
      - run: apt-get update
      - name: Install build prerequisites
        run: apt-get install -qy alex bzip2 gcc happy haskell-stack libbsd-dev libprotobuf-c-dev libutf8proc-dev make uuid-dev zlib1g-dev
      - name: chown our home dir to avoid stack complaining
        run: chown -R root:root /github/home
      - name: Build Acton
        run: make -C ${GITHUB_WORKSPACE}
      - name: Build a release
        run: make -C ${GITHUB_WORKSPACE} release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: acton-linux
          path: ${{ github.workspace }}/acton-linux-x86_64*
          if-no-files-found: error
      - name: Run tests
        run: make -C ${GITHUB_WORKSPACE} test

  release:
    runs-on: ubuntu-latest
    needs: [test-darwin, test-linux]
    steps:
      - run: echo "Doing a release, yay! 🎉"
      - name: "Check out repository code"
        uses: actions/checkout@v2
      - name: "Download artifacts for darwin / macos-11"
        uses: actions/download-artifact@v2
        with:
          name: acton-macos-11
      - name: "Download artifacts for linux"
        uses: actions/download-artifact@v2
        with:
          name: acton-linux
      - name: "Extract release notes"
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: acton*.tar*
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
